export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const UPDATE_USER = 'UPDATE_USER' 

export const UPDATE_SEARCH = 'UPDATE_SEARCH'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'
export const UPDATE_RESULT = 'UPDATE_RESULT'
export const START_SEARCH_LOADING = 'START_SEARCH_LOADING'
export const UPDATE_SLOTCHOOSEN = 'UPDATE_SLOTCHOOSEN'

